codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "50..100"

  status:
    project:
      default:
        target: auto
        threshold: 5%
        base: auto
        if_ci_failed: error
    patch:
      default:
        target: auto
        threshold: 5%
        base: auto
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "tests/**"
  - "samples/**"
  - "**/obj/**"
  - "**/bin/**"
  - "**/*.Tests/**"
  - "**/*.IntegrationTests/**"
  - "**/*.Sample/**"
  - "**/*.MultiProvider/**"

